import { ActivityIcon } from '@sanity/icons';
import { defineField, defineType } from 'sanity';

/**
 * PropertyAnalysis — AI-generated scoring and analysis for a property.
 * Separate document linked to Property via reference.
 *
 * Based on data contract: /scoring-spec/data-contract-scoring
 * Generated by the scoring model using property data + user preferences.
 *
 * Key design decisions:
 * - Separate from Property to allow re-scoring without touching listing data
 * - Per-criterium scores for UI transparency ("why did this score high/low?")
 * - 13 renovation categories with cost ranges
 * - VvE data parsed from pyfunda characteristics
 */
export const propertyAnalysis = defineType({
  name: 'propertyAnalysis',
  title: 'Woning Analyse',
  type: 'document',
  icon: ActivityIcon,
  groups: [
    { name: 'score', title: 'Score', default: true },
    { name: 'hardCriteria', title: 'Harde Criteria' },
    { name: 'softCriteria', title: 'Zachte Criteria' },
    { name: 'renovation', title: 'Renovatie' },
    { name: 'financial', title: 'Financieel' },
    { name: 'risk', title: 'Risico' },
    { name: 'meta', title: 'Meta' },
  ],
  fields: [
    // --- Reference ---
    defineField({
      name: 'property',
      title: 'Woning',
      type: 'reference',
      to: [{ type: 'property' }],
      validation: (rule) => rule.required(),
      group: 'score',
    }),
    defineField({
      name: 'searchProfile',
      title: 'Zoekprofiel',
      type: 'reference',
      to: [{ type: 'searchProfile' }],
      description: 'Tegen welk zoekprofiel is gescoord?',
      validation: (rule) => rule.required(),
      group: 'score',
    }),

    // --- Overall Score ---
    defineField({
      name: 'matchScore',
      title: 'Match Score',
      type: 'number',
      description: '0-100 overall match score',
      validation: (rule) => rule.required().min(0).max(100),
      group: 'score',
    }),
    defineField({
      name: 'tier',
      title: 'Tier',
      type: 'string',
      options: {
        list: [
          { title: '🏆 Topmatch', value: 'top_match' },
          { title: '👍 Goede match', value: 'good_match' },
          { title: '🤔 Redelijke match', value: 'reasonable_match' },
          { title: '👎 Slechte match', value: 'poor_match' },
          { title: '🚫 Niet geschikt', value: 'not_suitable' },
        ],
      },
      validation: (rule) => rule.required(),
      group: 'score',
    }),
    defineField({
      name: 'recommendation',
      title: 'Aanbeveling',
      type: 'string',
      options: {
        list: [
          { title: 'Direct bezichtigen', value: 'visit_immediately' },
          { title: 'Bezichtigen', value: 'worth_visiting' },
          { title: 'Nader onderzoek', value: 'needs_research' },
          { title: 'Overslaan', value: 'skip' },
        ],
      },
      group: 'score',
    }),
    defineField({
      name: 'summary',
      title: 'Samenvatting',
      type: 'text',
      description: 'AI-gegenereerde samenvatting van de analyse',
      group: 'score',
    }),

    // --- Hard Criteria (pass/fail) ---
    defineField({
      name: 'hardCriteriaPass',
      title: 'Alle harde criteria gehaald?',
      type: 'boolean',
      group: 'hardCriteria',
    }),
    defineField({
      name: 'hardCriteriaResults',
      title: 'Harde criteria resultaten',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'criterion',
              title: 'Criterium',
              type: 'string',
              options: {
                list: [
                  { title: 'Maximumprijs', value: 'max_price' },
                  { title: 'Minimale oppervlakte', value: 'min_living_area' },
                  { title: 'Minimaal kamers', value: 'min_rooms' },
                  { title: 'Minimaal slaapkamers', value: 'min_bedrooms' },
                  { title: 'Woningtype', value: 'property_type' },
                  { title: 'Locatie', value: 'location' },
                  { title: 'Must-have kenmerken', value: 'must_have_features' },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'pass',
              title: 'Gehaald',
              type: 'boolean',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'actualValue',
              title: 'Werkelijke waarde',
              type: 'string',
            }),
            defineField({
              name: 'requiredValue',
              title: 'Vereiste waarde',
              type: 'string',
            }),
            defineField({
              name: 'reasoning',
              title: 'Toelichting',
              type: 'string',
            }),
          ],
          preview: {
            select: {
              criterion: 'criterion',
              pass: 'pass',
            },
            prepare({ criterion, pass }) {
              return {
                title: `${pass ? '✅' : '❌'} ${criterion}`,
              };
            },
          },
        },
      ],
      group: 'hardCriteria',
    }),

    // --- Soft Criteria (weighted scores) ---
    defineField({
      name: 'softCriteriaScore',
      title: 'Zachte criteria score',
      type: 'number',
      description: 'Gewogen gemiddelde van zachte criteria (0-100)',
      validation: (rule) => rule.min(0).max(100),
      group: 'softCriteria',
    }),
    defineField({
      name: 'softCriteriaResults',
      title: 'Zachte criteria resultaten',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'criterion',
              title: 'Criterium',
              type: 'string',
              options: {
                list: [
                  { title: 'Energielabel', value: 'energy_label' },
                  { title: 'Bouwjaar', value: 'build_year' },
                  { title: 'Tuin', value: 'garden' },
                  { title: 'Balkon', value: 'balcony' },
                  { title: 'Parkeren', value: 'parking' },
                  { title: 'Buitenruimte', value: 'outdoor_space' },
                  { title: 'Staat van onderhoud', value: 'condition' },
                  { title: 'Buurt score', value: 'neighborhood_score' },
                  { title: 'Prijs/m²', value: 'price_per_sqm' },
                  { title: 'Dagen op markt', value: 'days_on_market' },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'score',
              title: 'Score',
              type: 'number',
              description: '0-100',
              validation: (rule) => rule.required().min(0).max(100),
            }),
            defineField({
              name: 'weight',
              title: 'Gewicht',
              type: 'number',
              description: 'Gewicht van dit criterium (0-1)',
              validation: (rule) => rule.min(0).max(1),
            }),
            defineField({
              name: 'weightedScore',
              title: 'Gewogen score',
              type: 'number',
              description: 'score × weight',
            }),
            defineField({
              name: 'reasoning',
              title: 'Toelichting',
              type: 'string',
            }),
          ],
          preview: {
            select: {
              criterion: 'criterion',
              score: 'score',
            },
            prepare({ criterion, score }) {
              return {
                title: `${criterion}: ${score}/100`,
              };
            },
          },
        },
      ],
      group: 'softCriteria',
    }),

    // --- Renovation Assessment ---
    defineField({
      name: 'overallCondition',
      title: 'Algehele staat',
      type: 'string',
      options: {
        list: [
          { title: 'Uitstekend', value: 'excellent' },
          { title: 'Goed', value: 'good' },
          { title: 'Redelijk', value: 'fair' },
          { title: 'Matig', value: 'poor' },
          { title: 'Slecht', value: 'bad' },
        ],
      },
      group: 'renovation',
    }),
    defineField({
      name: 'totalRenovationCostLow',
      title: 'Totale renovatiekosten (laag)',
      type: 'number',
      group: 'renovation',
    }),
    defineField({
      name: 'totalRenovationCostMid',
      title: 'Totale renovatiekosten (midden)',
      type: 'number',
      group: 'renovation',
    }),
    defineField({
      name: 'totalRenovationCostHigh',
      title: 'Totale renovatiekosten (hoog)',
      type: 'number',
      group: 'renovation',
    }),
    defineField({
      name: 'renovationBreakdown',
      title: 'Renovatie per categorie',
      type: 'array',
      description: '13 categorieën: keuken, badkamer, vloeren, schilderwerk, dak, isolatie, ramen, elektra, leidingwerk, CV-ketel, tuin, kozijnen, overig',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'category',
              title: 'Categorie',
              type: 'string',
              options: {
                list: [
                  { title: 'Keuken', value: 'keuken' },
                  { title: 'Badkamer', value: 'badkamer' },
                  { title: 'Vloeren', value: 'vloeren' },
                  { title: 'Schilderwerk', value: 'schilderwerk' },
                  { title: 'Dak', value: 'dak' },
                  { title: 'Isolatie', value: 'isolatie' },
                  { title: 'Ramen & kozijnen', value: 'ramen_kozijnen' },
                  { title: 'Elektra', value: 'elektra' },
                  { title: 'Leidingwerk', value: 'leidingwerk' },
                  { title: 'CV-ketel', value: 'cv_ketel' },
                  { title: 'Tuin', value: 'tuin' },
                  { title: 'Kozijnen', value: 'kozijnen' },
                  { title: 'Overig', value: 'overig' },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'needed',
              title: 'Nodig',
              type: 'string',
              options: {
                list: [
                  { title: 'Niet nodig', value: 'not_needed' },
                  { title: 'Optioneel', value: 'optional' },
                  { title: 'Aanbevolen', value: 'recommended' },
                  { title: 'Vereist', value: 'required' },
                ],
              },
              initialValue: 'not_needed',
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'costLow',
              title: 'Kosten (laag)',
              type: 'number',
            }),
            defineField({
              name: 'costMid',
              title: 'Kosten (midden)',
              type: 'number',
            }),
            defineField({
              name: 'costHigh',
              title: 'Kosten (hoog)',
              type: 'number',
            }),
            defineField({
              name: 'reasoning',
              title: 'Toelichting',
              type: 'string',
            }),
          ],
          preview: {
            select: {
              category: 'category',
              needed: 'needed',
              costMid: 'costMid',
            },
            prepare({ category, needed, costMid }) {
              if (needed === 'not_needed') return { title: `✅ ${category}: niet nodig` };
              const emoji = needed === 'required' ? '🔴' : needed === 'recommended' ? '🟡' : '🔵';
              const cost = costMid ? `€${(costMid / 1000).toFixed(0)}k` : '';
              return { title: `${emoji} ${category}: ${cost}` };
            },
          },
        },
      ],
      group: 'renovation',
    }),

    // --- Financial Impact ---
    defineField({
      name: 'totalInvestment',
      title: 'Totale investering',
      type: 'number',
      description: 'Vraagprijs + kosten koper + renovatie (mid estimate)',
      group: 'financial',
    }),
    defineField({
      name: 'kostenKoper',
      title: 'Kosten koper',
      type: 'number',
      description: 'Overdrachtsbelasting + notaris + makelaar',
      group: 'financial',
    }),
    defineField({
      name: 'monthlyMortgage',
      title: 'Geschatte maandlasten hypotheek',
      type: 'number',
      group: 'financial',
    }),
    defineField({
      name: 'monthlyTotal',
      title: 'Totale maandlasten',
      type: 'number',
      description: 'Hypotheek + servicekosten + erfpacht',
      group: 'financial',
    }),
    defineField({
      name: 'erfpachtNpv',
      title: 'Erfpacht NPV',
      type: 'number',
      description: 'Netto contante waarde van erfpachtverplichtingen',
      group: 'financial',
    }),
    defineField({
      name: 'withinBudget',
      title: 'Binnen budget',
      type: 'boolean',
      group: 'financial',
    }),
    defineField({
      name: 'budgetRemaining',
      title: 'Budget resterend',
      type: 'number',
      description: 'maxTotalCost - totalInvestment (negatief = over budget)',
      group: 'financial',
    }),

    // --- Risk Assessment ---
    defineField({
      name: 'overallRiskLevel',
      title: 'Algeheel risiconiveau',
      type: 'string',
      options: {
        list: [
          { title: '🟢 Laag', value: 'low' },
          { title: '🟡 Gemiddeld', value: 'medium' },
          { title: '🔴 Hoog', value: 'high' },
        ],
      },
      group: 'risk',
    }),
    defineField({
      name: 'risks',
      title: 'Risicofactoren',
      type: 'array',
      of: [
        {
          type: 'object',
          fields: [
            defineField({
              name: 'category',
              title: 'Categorie',
              type: 'string',
              options: {
                list: [
                  { title: 'VvE', value: 'vve' },
                  { title: 'Erfpacht', value: 'erfpacht' },
                  { title: 'Fundering', value: 'fundering' },
                  { title: 'Asbest', value: 'asbest' },
                  { title: 'Bodemverontreiniging', value: 'bodem' },
                  { title: 'Bestemmingsplan', value: 'bestemmingsplan' },
                  { title: 'Overstroming', value: 'overstroming' },
                  { title: 'Markt', value: 'markt' },
                  { title: 'Overig', value: 'overig' },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'level',
              title: 'Niveau',
              type: 'string',
              options: {
                list: [
                  { title: 'Laag', value: 'low' },
                  { title: 'Gemiddeld', value: 'medium' },
                  { title: 'Hoog', value: 'high' },
                ],
              },
              validation: (rule) => rule.required(),
            }),
            defineField({
              name: 'description',
              title: 'Beschrijving',
              type: 'string',
            }),
            defineField({
              name: 'mitigation',
              title: 'Mitigatie',
              type: 'string',
              description: 'Wat kun je eraan doen?',
            }),
          ],
          preview: {
            select: {
              category: 'category',
              level: 'level',
            },
            prepare({ category, level }) {
              const emoji =
                level === 'high' ? '🔴' : level === 'medium' ? '🟡' : '🟢';
              return { title: `${emoji} ${category}` };
            },
          },
        },
      ],
      group: 'risk',
    }),

    // --- VvE Data (parsed from pyfunda) ---
    defineField({
      name: 'vveData',
      title: 'VvE Data',
      type: 'object',
      group: 'risk',
      fields: [
        defineField({
          name: 'monthlyContribution',
          title: 'Maandelijkse bijdrage (€)',
          type: 'number',
        }),
        defineField({
          name: 'hasReserveFund',
          title: 'Reservefonds aanwezig',
          type: 'boolean',
        }),
        defineField({
          name: 'hasMaintenancePlan',
          title: 'Onderhoudsplan aanwezig',
          type: 'boolean',
        }),
        defineField({
          name: 'kvkRegistered',
          title: 'Ingeschreven KvK',
          type: 'boolean',
        }),
        defineField({
          name: 'hasBuildingInsurance',
          title: 'Opstalverzekering',
          type: 'boolean',
        }),
      ],
      options: {
        collapsible: true,
        collapsed: false,
      },
    }),

    // --- Dealbreakers ---
    defineField({
      name: 'dealbreakers',
      title: 'Dealbreakers',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'Lijst van gevonden dealbreakers (indien aanwezig)',
      group: 'risk',
    }),

    // --- Meta ---
    defineField({
      name: 'analyzedAt',
      title: 'Geanalyseerd op',
      type: 'datetime',
      validation: (rule) => rule.required(),
      group: 'meta',
    }),
    defineField({
      name: 'modelVersion',
      title: 'Model versie',
      type: 'string',
      description: 'Versie van het scoring model',
      group: 'meta',
    }),
    defineField({
      name: 'openaiModel',
      title: 'OpenAI model',
      type: 'string',
      description: 'Welk OpenAI model is gebruikt',
      group: 'meta',
    }),
    defineField({
      name: 'processingTimeMs',
      title: 'Verwerkingstijd (ms)',
      type: 'number',
      group: 'meta',
    }),
  ],
  orderings: [
    {
      title: 'Score (hoog → laag)',
      name: 'scoreDesc',
      by: [{ field: 'matchScore', direction: 'desc' }],
    },
    {
      title: 'Nieuwste eerst',
      name: 'dateDesc',
      by: [{ field: 'analyzedAt', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      address: 'property.address',
      city: 'property.city',
      score: 'matchScore',
      tier: 'tier',
      analyzedAt: 'analyzedAt',
    },
    prepare({ address, city, score, tier, analyzedAt }) {
      const tierEmoji =
        tier === 'top_match'
          ? '🏆'
          : tier === 'good_match'
            ? '👍'
            : tier === 'reasonable_match'
              ? '🤔'
              : tier === 'poor_match'
                ? '👎'
                : '🚫';
      const date = analyzedAt
        ? new Date(analyzedAt).toLocaleDateString('nl-NL')
        : '';
      return {
        title: `${tierEmoji} ${score}/100 — ${address || 'Onbekend'}`,
        subtitle: `${city || ''} · ${date}`,
      };
    },
  },
});
